apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: food-web
  template:
    metadata:
      labels:
        app: food-web
    spec:
      containers:
        - name: food-web
          image: setthi001/food:01
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
